import type { Metadata } from "next";
import "./globals.css";
import {ClerkProvider} from "@clerk/nextjs";
import {Providers} from "./providers";




export const metadata: Metadata = {
  title: "Next UI App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
      <ClerkProvider afterSignOutUrl="/">
        <Providers>
          {children}
        </Providers>
        </ClerkProvider>
      </body>
    </html>
  );
}
